// <auto-generated />
using Domain.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(ExcelManagerDBContext))]
    partial class ExcelManagerDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.DailyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Absence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllowedDelay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EarlyDeparture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunctionList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LateArrival")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeaveBonus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeaveEntitlement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeaveHourly")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeaveMedical")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeaveOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeaveUnpaid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissionDaily")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissionHourly")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NightShift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OvertimeHoliday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OvertimeMission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OvertimeTotal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Performance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transit1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transit2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transit3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transit4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transit5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transit6")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DailyRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
